spring.application.name=PreProject3

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/project_test
spring.datasource.username=root
spring.datasource.password=root


# ===== НАСТРОЙКИ JPA/HIBERNATE =====
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Оптимизации
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.main.lazy-initialization=false

# ===== НАСТРОЙКИ БЕЗОПАСНОСТИ =====
# Пароли по умолчанию для тестовых пользователей
app.default.admin.password=admin
app.default.user.password=user

# ===== НАСТРОЙКИ ЛОГИРОВАНИЯ =====

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG



# Настройки ротации логов
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=100MB

# ===== НАСТРОЙКИ ДЛЯ РАЗРАБОТКИ =====
spring.profiles.active=dev
spring.thymeleaf.cache=false
# Включение DevTools (обычно включено по умолчанию)
spring.devtools.restart.enabled=true
# Исключение ненужных файлов из перезагрузки
spring.devtools.restart.exclude=static/**,templates/**

# Spring Security (перенаправления уже настроены в Java-конфиге)
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN

# Настройка статических ресурсов
spring.mvc.static-path-pattern=/resources/**

# Главная страница
spring.web.resources.static-locations=classpath:/static/,classpath:/templates/

# Временно отключите security для теста
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
logging.file.name=logs\\spring.log
## ===== ПРОФИЛЬ PROD (активируется через --spring.profiles.active=prod) =====
#---
#spring.profiles=prod
#spring.jpa.hibernate.ddl-auto=validate
#spring.thymeleaf.cache=true
#logging.level.root=WARN
#logging.level.org.springframework.security=WARN

# Validation messages
user.username.notblank=Логин не может быть пустым
user.username.size=Логин должен быть от {min} до {max} символов
user.password.notblank=Пароль не может быть пустым
user.password.size=Пароль должен содержать минимум {min} символов
user.roles.notempty=Необходимо выбрать хотя бы одну роль

spring.main.allow-circular-references=false